### ISSUE TITLE
Highscore reporting is broken, stuck after completing one game.

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/pinball#468]
Can't actually continue after you complete one round as high scores won't submit.  You have to reload the page to continue.

![image](https://user-images.githubusercontent.com/11857803/167749159-0c19779d-3369-4fec-a01e-fd1e8e841770.png)

**Comment by eseidelGoogle** [comment]
Possibly due to https://github.com/flutter/pinball/pull/467 ?

**Comment by GroovinChip** [comment]
Can confirm this happens for me too, no matter what combination of letters I use. Happens on multiple machines as well.

**Comment by tomarra** [comment]
This was fixed via #469. There are for sure more steps that can be taken to make the app more robust here but the immediate need to get things back up and running was completed.

@eseidelGoogle if you could confirm and close that would be great.

**Comment by eseidelGoogle** [comment]
Sg.  I do think we will probably want to move to a more robust-against-failure model on the client (assuming we're going to end up paying less day-to-day attention to pinball soon), but that can be considered/prioritized separately from this break.  Thanks!
