### ISSUE TITLE
Flippers occasionally clip through ball

### ISSUE THREAD

**Issue by Skylled** [flutter/pinball#470]
Sometimes (often when the ball has a bit of momentum) the flippers will simply clip through the ball instead of hitting it.

I snagged a recording of it happening once.

Platform: Chrome OS version 101

![pinball-clip-through-flipper](https://user-images.githubusercontent.com/13603296/167772301-45ea997f-7922-4b8c-8294-6e206bb15ad5.gif)

**Comment by PieterAelse** [comment]
I saw this too, twice, on mobile.

**Comment by alestiago** [comment]
@Skylled thanks for the issue. I would appreciate it if you playtest the branch in #483 and see if you:

1. Still see this behaviour
2. Have performance impacts

**Comment by Skylled** [comment]
Built your branch and tried it on my local device. After playing for about an hour, I didn't notice any instances of clipping.

Jury's still out on the performance hit. With a single ball in play, it seems to be the same, but when I managed to get about 4 in play, CPU usage doubled and game speed slowed down. Still trying to recreate that slowdown.

**Comment by alestiago** [comment]
@Skylled thanks for looking into it. I didn't experience any performance hit on my machine (MacBook Pro M1) with over 30 balls.

If you're on debug mode you can tap the board to spawn balls. Be careful spamming since if your user input is done whilst the world is locked (processing) you'll get thrown an assertion error due to the world being locked (this is a known issue in FlameForge2D).

**Comment by Skylled** [comment]
I don't have anything handy that's lower-powered than an Intel i5, but the performance issue noted seems to have been a one off. I enabled the debug table in release mode (to ensure all relevant performance boosts were enabled) and only noticed a slowdown with a number of pinballs not likely to be reached in normal play.

Looks great and plays well. Thanks for fixing this. :)

**Comment by alestiago** [comment]
@Skylled sinxe the fix PR has been merged, do you think this issue can be closed since it's resolved?

I don't know when the next deployment will be done but hopefully we see it live sometime soon.
