### ISSUE TITLE
Windows desktop app crashes (no Firebase)

### ISSUE THREAD

**Issue by msveshnikov** [flutter/pinball#488]
[log] [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
[log] #0      MethodChannelFirebase.app

Web is working if I put credentials to web/.../init.js

Where to put for Windows Desktop?

**Comment by msveshnikov** [comment]
Seems like here: https://pub.dev/packages/firebase_auth_desktop

**Comment by thatfiredev** [comment]
I don't think Firebase for flutter supports Windows Desktop yet.
The available plugins table only mentions Android, iOS and Web: https://firebase.google.com/docs/flutter/setup?platform=android#available-plugins

**Comment by alestiago** [comment]
Thanks @msveshnikov for opening an issue! Also thank you @thatfiredev for your answer!

@msveshnikov do we think this issue is now resolved, so it can be closed?

**Comment by msveshnikov** [comment]
Yes, now it is clear 😎
