### ISSUE TITLE
dashbook dependency is maybe missing

### ISSUE THREAD

**Issue by derKosi** [flutter/pinball#491]
flutter pub add dashbook

because 

is is missing, i think in
https://github.com/flutter/pinball/blob/main/packages/pinball_components/sandbox/pubspec.yaml

and requested by
https://github.com/flutter/pinball/blob/main/packages/pinball_components/sandbox/lib/main.dart

Maybe I am looking at the wrong place, bacause the test should have not passed this not building version.
Maybe the dependency file needs the 'excatly right' versions, not just the package name.

I am sorry, but I am pretty new here, and have no time right now, thats why my ticket is not up to par.

Fresh VSCode and flutter install on win10, (with VS2022 Pre c++ Toolchain)

and I crash (on 'nuget restore in pup-world') because out of low memory, when some programs are running (Teamviewer, Chome), but that is unrelated to dashbook and happens with other Applications as well.

**Comment by erickzanardo** [comment]
Hey,

Dashbook is listed on the pubspec as you can see here on this line: https://github.com/flutter/pinball/blob/main/packages/pinball_components/sandbox/pubspec.yaml#L10

Maybe we are just missing a `flutter pub get` to fetch the dependencies?

**Comment by derKosi** [comment]
Well, it 'builds', so it's not too bad.
Maybe my 'flutter pub get' earlier crashed.

I just thought the squiggly lines aren't too good,
but maybe that is the 'linter' or 'vscode'.

Also, i was not aware that 8GB Ram could not be enough
because I get no output in chrome, but that is maybe my setup.
If I will still be interested in flutter in a few days I will give it a big VM and see if a 'clean run' will work.
Maybe tha ram thing is 'flame' issue.


Well, after adding and removind dashbook it fails to build.
I will restart my machine and take a closer look, this cannot be right. and it is probably me.

I will close this ticket, since dashbook is in the sandbox.pubspec, but i will spin up a VM in the cloud,
and try this again today.

Sorry for going off topic here by the way. If this Issue is not helpfull, feel free to delete the whole thing.

**Comment by derKosi** [comment]
Okay, after a fresh 'git clone' and 'flutter pub get' the pinball started, and after re-adding the firebase init data ( https://github.com/flutter/pinball/commit/f04808dc3657952779645a186af3d30c84b5859e )
it also started and I could finally play.

I would suggest you invalidate the apikey and redeploy to https://pinball.flutter.de , though.

But there are still alot of squiggly lines in the sandbox component.

**Comment by AristideVB** [comment]
Same issue here a fresh 'git clone' neither 'flutter clean && flutter pub get' solved my issue
